### ISSUE TITLE
[feat] : 주최자는 행사를 관리할 수 있다

### ISSUE THREAD

**Issue by bbbang105** [skatch-devocean-young/backend#22]
### 📝 Description

- 주최자는 행사를 관리할 수 있다

---

### 📝 Todo

- [x] 행사 전체 조회 API
- [x] 행사 상세 조회 API
- [x] 행사 등록 API
- [x] 행사 수정 API
- [x] 행사 삭제 API
