### ISSUE TITLE
[feat] : 회원가입을 구현한다

### ISSUE THREAD

**Issue by Ganghee-Lee-0522** [skatch-devocean-young/backend#26]
### 📝 Description

- 본인인증(소셜로그인)
- 회원등록(오거나이저/일반유저)
- 추가정보등록(오거나이저)

---

### 📝 Todo

- [ ] 카카오 인증
- [ ] 회원가입(이름, 전화번호, role)
- [x] 추가정보등록(아티스트명, 장르, 멤버, 대표곡, 한줄소개, 프로필사진)
- [ ] 추가정보 테이블 생성
