### ISSUE TITLE
[chore] : swagger ui를 설정한다

### ISSUE THREAD

**Issue by Ganghee-Lee-0522** [skatch-devocean-young/backend#41]
### 📝 Description

- 추가 구현한 api의 swagger를 작성한다.

---

### 📝 Todo

- [ ] /api/v1/events/action-apply/{events_id}
- [ ] /api/v1/events/action-apply/{events_id}
- [ ] /api/v1/events/action-apply/attend
- [ ] /api/v1/ticket/{attendee_id}
- [ ] /api/v1/ticket/list
