### ISSUE TITLE
[feat] : submodule로 config 파일 관리

### ISSUE THREAD

**Issue by Ganghee-Lee-0522** [skatch-devocean-young/backend#7]
### 📝 Description

- private repository 생성하기
- private repository 연결하기

---

### 📝 Todo

- [x] private repo 생성
- [x] private repo에 config 파일 생성
- [x] main repo로 pr
- [x] merge
