### ISSUE TITLE
[feat] : 공통 응답 dto 세팅

### ISSUE THREAD

**Issue by Ganghee-Lee-0522** [skatch-devocean-young/backend#9]
### 📝 Description

- 공통 응답을 위한 dto 및 관련 enum 생성

---

### 📝 Todo

- [x] ApiResponse record 생성
- [x] ExceptionDto record 생성
- [x] ErrorCode(사용자 정의 예외) enum 생성
- [x] ResponseStatusCodeSetterAdvice(Header status code 세팅) class 생성
- [x] CustomException(예외 로그 대비) class 생성
- [x] GlobalExceptionHandler(전역적인 예외 처리) class 생성
- [x] static resource mapping(NoHandlerFoundException 방지) yml file 생성

**Comment by Ganghee-Lee-0522** [comment]
공통 응답 DTO가 없어서 작업이 어려워 그냥 만들겠습니다 @bbbang105

**Comment by Ganghee-Lee-0522** [comment]
브랜치 머지 후 yml 파일 추가 생성 작업 진행할 예정
